; leafy Base Stats
; Auto-generated by PokeGen

db   45            ; HP
db   49        ; Attack
db   49       ; Defense
db   65        ; Special Attack
db   65        ; Special Defense
db   45         ; Speed

db  11, 11      ; Type1, Type2

db  50        ; Gender ratio (0=always M, 100=always F)
db  100       ; Catch rate
db  95    ; Base Experience (estimate)

db  GROWTH_MEDIUM_FAST  ; Growth rate
db  NO_ITEM             ; Item 1
db  NO_ITEM             ; Item 2

db  100                 ; Egg cycles

; Abilities
db  1, 0