; leafy Evolutions and Moves
; Auto-generated by PokeGen

; Evolutions (none for custom Pokémon)
db  0  ; No evolutions defined

; Learnset (generated moves)
db 9, ICE_BEAM
db 17, POWER_TRIP
db 18, CONFUSION
db 19, SKILL_SWAP
db 20, OMINOUS_WIND
db 21, SHELL_SMASH
db 22, SWITCHAROO
db 23, QUICK_ATTACK
db 25, HEADBUTT
db 26, SOLAR_BEAM
db 31, AGILITY
db 43, YAWN
db 0, 0    ; End learnset