; UI_AutoTest2 Base Stats
; Auto-generated by PokeGen

db   65            ; HP
db   80        ; Attack
db   70       ; Defense
db   85        ; Special Attack
db   60        ; Special Defense
db   75         ; Speed

db  15, 15      ; Type1, Type2

db  50        ; Gender ratio (0=always M, 100=always F)
db  100       ; Catch rate
db  135   ; Base Experience (estimate)

db  GROWTH_MEDIUM_FAST  ; Growth rate
db  NO_ITEM             ; Item 1
db  NO_ITEM             ; Item 2

db  100                 ; Egg cycles

; Abilities
db  1, 0