; UI_AutoTest2 Evolutions and Moves
; Auto-generated by PokeGen

; Evolutions (none for custom Pokémon)
db  0  ; No evolutions defined

; Learnset (generated moves)
db 1, HYPER_BEAM
db 25, BITE
db 50, QUICK_ATTACK
db 75, TACKLE
db 100, GROWL
db 0, 0    ; End learnset