; sldk Evolutions and Moves
; Auto-generated by PokeGen

; Evolutions (none for custom Pokémon)
db  0  ; No evolutions defined

; Learnset (generated moves)
db 1, GROWL
db 25, TACKLE
db 50, QUICK_ATTACK
db 75, BITE
db 100, HYPER_BEAM
db 0, 0    ; End learnset