; TestMon Evolutions and Moves
; Auto-generated by PokeGen

; Evolutions (none for custom Pokémon)
db  0  ; No evolutions defined

; Learnset (basic moves)
db  TACKLE,  1
db  GROWL,   1
db  0, 0    ; End learnset