; Judas Evolutions and Moves
; Auto-generated by PokeGen

; Evolutions (none for custom Pokémon)
db  0  ; No evolutions defined

; Learnset (generated moves)
db 1, WILL_O_WISP
db 12, SUNNY_DAY
db 23, FIRE_SPIN
db 34, EMBER
db 45, FLAME_WHEEL
db 56, FIRE_PUNCH
db 67, FLAMETHROWER
db 78, SACRED_FIRE
db 89, FLARE_BLITZ
db 100, FIRE_BLAST
db 0, 0    ; End learnset