; UI_CheckPath Base Stats
; Auto-generated by PokeGen

db   50            ; HP
db   60        ; Attack
db   40       ; Defense
db   55        ; Special Attack
db   45        ; Special Defense
db   65         ; Speed

db  6 , 6       ; Type1, Type2

db  50        ; Gender ratio (0=always M, 100=always F)
db  100       ; Catch rate
db  105   ; Base Experience (estimate)

db  GROWTH_MEDIUM_FAST  ; Growth rate
db  NO_ITEM             ; Item 1
db  NO_ITEM             ; Item 2

db  100                 ; Egg cycles

; Abilities
db  1, 0