; UI_DiagTest2 Base Stats
; Auto-generated by PokeGen

db   60            ; HP
db   75        ; Attack
db   55       ; Defense
db   80        ; Special Attack
db   60        ; Special Defense
db   70         ; Speed

db  9 , 9       ; Type1, Type2

db  50        ; Gender ratio (0=always M, 100=always F)
db  100       ; Catch rate
db  125   ; Base Experience (estimate)

db  GROWTH_MEDIUM_FAST  ; Growth rate
db  NO_ITEM             ; Item 1
db  NO_ITEM             ; Item 2

db  100                 ; Egg cycles

; Abilities
db  1, 0